{
 "title": "Agoric Dashboard New Copy Copy Back",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   {
    "name": "agoric_instance",
    "label": "agoric_instance",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
    }
   },
   {
    "name": "agoric_job",
    "label": "agoric_job",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, job)"
    }
   },
   {
    "name": "node_instance",
    "label": "node_instance",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   },
   {
    "name": "node_job",
    "label": "node_job",
    "query": {
     "query": "label_values(node_exporter_build_info,job)"
    }
   },
   {
    "name": "validator_address",
    "label": "validator_address",
    "query": {
     "query": "label_values(tendermint_consensus_validator_power{chain_id=\"$chain_id\",instance=\"$agoric_instance\",job=\"$agoric_job\"},validator_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Agoric Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Num Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Block Size, B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Total TXS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Num TXS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Uncommited TXS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Validator Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{instance=\"$agoric_instance\",job=\"$agoric_job\",validator_address=\"$validator_address\"}"
    }
   ]
  },
  {
   "title": "Validator Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{instance=\"$agoric_instance\",job=\"$agoric_job\",validator_address=\"$validator_address\"}"
    }
   ]
  },
  {
   "title": "Byzantine+Missing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(tendermint_consensus_byzantine_validators{instance=\"$agoric_instance\",job=\"$agoric_job\"} + tendermint_consensus_missing_validators{instance=\"$agoric_instance\",job=\"$agoric_job\"})"
    }
   ]
  },
  {
   "title": "Avg Block Interval, s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / rate(tendermint_state_block_processing_time_count{instance=\"$agoric_instance\",job=\"$agoric_job\"}[5m])"
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tendermint_p2p_peer_send_bytes_total{instance=\"$agoric_instance\",job=\"$agoric_job\"}[1m]))",
     "legendFormat": "tendermint_p2p_peer_send_bytes_total"
    },
    {
     "expr": "-sum(rate(tendermint_p2p_peer_receive_bytes_total{instance=\"$agoric_instance\",job=\"$agoric_job\"}[1m]))",
     "legendFormat": "tendermint_p2p_peer_receive_bytes_total"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$agoric_instance\",job=\"$agoric_job\"}[1m])"
    }
   ]
  },
  {
   "title": "Mem Used, MB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$agoric_instance\",job=\"$agoric_job\"}/1024/1024"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_state_syncing{instance=\"$agoric_instance\",job=\"$agoric_job\"}"
    }
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } }
 ]
}